version: '3.8'
services:
  elasticsearch:
    volumes:
      - ./elasticsearch/config:/etc/elasticsearch
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  

  kibana:
    volumes:
      - ./kibana/config:/usr/share/kibana/config
      - ./kibana/logs:/var/log/kibana

  logstash:
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs/logstash:/var/log/logstash
      - ./app-log/Data:/usr/share/logstash/data
      - ./app-log/patterns:/usr/share/logstash/patterns
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m  

networks:
  elk:
    driver: bridge
