version: '3.8'
services:
  elasticsearch:
    env_file:
      - .env
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/config:/etc/elasticsearch
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    env_file:
      - .env
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config:/usr/share/kibana/config
      - ./kibana/logs:/var/log/kibana
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    env_file:
      - .env
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logs:/var/log/logstash
      - ./app-log/Data:/usr/share/logstash/data
      - ./app-log/patterns:/usr/share/logstash/patterns
    ports:
      - "5044:5044"
    networks:
      - elk

networks:
  elk:
    driver: bridge