version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    user: "0" 
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/config:/etc/elasticsearch
      - ./elasticsearch/logs:/usr/share/elasticsearch/config/logs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    command: >
      sh -c "chmod -R 777 /etc/elasticsearch /usr/share/elasticsearch/config/logs /usr/share/elasticsearch/data && /usr/local/bin/docker-entrypoint.sh"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    user: "0" 
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config:/etc/kibana/config
      - ./kibana/logs:/usr/share/kibana/config/logs
    command: >
      sh -c "chmod -R 777 /etc/kibana/config /usr/share/kibana/config/logs && /usr/local/bin/docker-entrypoint.sh"
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    user: "0" 
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config:/etc/logstash
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs/logstash:/usr/share/logstash/config/logs
      - ./app-log:/usr/share/logstash/data/
      - ./app-log/patterns:/usr/share/logstash/patterns/
    command: >
      sh -c "chmod -R 777 /etc/logstash /usr/share/logstash/pipeline /usr/share/logstash/config/logs /usr/share/logstash/config/logs /usr/share/logstash/data/ && /usr/local/bin/docker-entrypoint.sh"
    ports:
      - "5044:5044"
    networks:
      - elk

networks:
  elk:
    driver: bridge