version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/config:/etc/elasticsearch
      #- ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config:/etc/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config:/etc/logstash
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./app-log:/usr/share/logstash/data/
      - ./app-log/patterns:/usr/share/logstash/patterns/
    ports:
      - "5044:5044"
    networks:
      - elk

networks:
  elk:
    driver: bridge