server.host: "0.0.0.0"
elasticsearch.hosts: ["http://localhost:9200"]

# elasticsearch.username: "kibana"
# elasticsearch.password: "0wUv6x7PCetch"

logging:
  appenders:
    file:
      type: file
      fileName: /usr/share/kibana/config/logs/kibana.log
      layout:
        type: json
  root:
    appenders:
      - file
