server.host: "0.0.0.0"
elasticsearch.hosts: ["https://elasticsearch:9200"]

elasticsearch.username: "elastic"
elasticsearch.password: "changeme"

elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/cert/elastic-certificates.p12"]

elasticsearch.ssl.verificationMode: certificate
